Fix members grid CSS
urish/pull-request-community pull request #102
Opened 2021-03-26 13:27 UTC by idomand

#93 
Hi,
I've solved the problem by changing the layout of the page from flaxbox into grid. 
I've also added a card with my details.

Unfortunately, this change had disabled the “show more” transition animation. but after talking to @MichalPorag about it she mentioned that since issue #98 is to change that animation anyway I could push this change now.

Attached below are the before and after pictures.

![BeforeChange](https://user-images.githubusercontent.com/63243268/112637861-a400ab80-8e4f-11eb-8575-e9d479667d1b.JPG)
![EndResult](https://user-images.githubusercontent.com/63243268/112637863-a531d880-8e4f-11eb-9379-0b38d00fab96.JPG)

2021-03-26 14:49 UTC, MichalPorag requested changes
Great work!

Please change the logic so the width and height of the card will be the maximum size of the cell
![image](https://user-images.githubusercontent.com/47606575/112648830-f5626800-8e5a-11eb-9a4b-9d4c572a3d4e.png)

This way the gap will stay the same in all screen size.

Hint : you have gap row and column as well as gap and if you want to write it in one line you can use:
"gap: column-size row-size;".

Good luck :)

2021-03-26 14:49 UTC, MichalPorag commented on people/idomand.json
> +}
This is not related to this issue, please open it in new branch

2021-03-30 09:38 UTC, idomand commented
Hi @MichalPorag,

I have separated the extra json file into a different branch and fixed the grid-gap and the height and width of the cards as you requested.

2021-04-01 12:40 UTC, MichalPorag requested changes
@idomand 
Great job!
We are getting closer, just a little bit improvements :) 

After you change that things, please check out the card height issue and the gap issue.

Hint: you need to remove the duplication gap declaration.

2021-04-01 12:40 UTC, MichalPorag commented on styles/Home.module.scss
>  @media only screen and (max-width: $smTablet) {
You can remove all the media query from here

2021-04-01 12:40 UTC, MichalPorag commented on components/personCard/personCard.module.scss
> +  min-width: 550px;
You can remove this

2021-04-01 12:40 UTC, MichalPorag commented on styles/Home.module.scss
> +    grid-template-columns: repeat(auto-fit, minmax(550px, 1fr));
Please change to minmax(350px, 1fr)

2021-04-01 17:49 UTC, MichalPorag approved these changes

2021-04-01 17:49 UTC, merged