Adding an explanation on how to set an upstream, creating a specified branch for docs
urish/pull-request-community pull request #55
Opened 2021-02-10 22:34 UTC by lesagi

2021-02-11 06:35 UTC, MichalPorag requested changes
תודה רבה על התרומה! 
כתבתי לך כמה הערות קטנות :)

2021-02-11 06:35 UTC, MichalPorag commented on people/lesagi.json
> +  "description": "מפתח פולסטאק, אוהב שפות, אוהב אלגוריתמים ועושה צעדים ראשונים בתרומה לקוד פתוח"
אשמח אם תוכל לפרט קצת יותר על עצמך, תחומי עניין, תחביבים, דברים שמלהיבים אותך ולא רק על תוכנה :) 
ככה נוכל להכיר אותך יותר, אם אתה לא רוצה תכתוב בתגובה ואני אאשר לך את זה ככה.

2021-02-11 06:35 UTC, MichalPorag commented on people/lesagi.json
> +  "facebook": "https://www.facebook.com/lesagi3/",
הלינק שבור

2021-02-11 07:06 UTC, lesagi commented on people/lesagi.json
> +  "facebook": "https://www.facebook.com/lesagi3/",
הי, הלינק עובד... יכול להיות שלא העתקת את כולו?

2021-02-11 07:07 UTC, lesagi commented on people/lesagi.json
> +  "description": "מפתח פולסטאק, אוהב שפות, אוהב אלגוריתמים ועושה צעדים ראשונים בתרומה לקוד פתוח"
הי, זה שגיא מהמפגש אתמול, האמת שזה לא השינוי האחרון שהצעתי... זה כבר אושר
(אני כבר מופיע באתר)

אני הוספתי את התיקון לאפסטרים ברידמי.... אבל איכשהו כל פי.אר שאני פותח מתווסף לכאן, למרות שיש כאן קומיטים שכבר אושרו...
יודעת להגיד לי למה?

2021-02-11 07:09 UTC, MichalPorag commented on people/lesagi.json
> +  "facebook": "https://www.facebook.com/lesagi3/",
באמת עובד עכשיו, יכול להיות. תודה

2021-02-11 07:10 UTC, MichalPorag commented on people/lesagi.json
> +  "description": "מפתח פולסטאק, אוהב שפות, אוהב אלגוריתמים ועושה צעדים ראשונים בתרומה לקוד פתוח"
אני זוכרת אותך, זיהיתי אותך ישר :)
אתה פותח אותו עם אותו הברנץ׳?

2021-02-11 07:12 UTC, lesagi commented on people/lesagi.json
> +  "description": "מפתח פולסטאק, אוהב שפות, אוהב אלגוריתמים ועושה צעדים ראשונים בתרומה לקוד פתוח"
בארנץ׳ אחר לגמרי (אפילו ציינתי בכותרת הפי.אר החדש), קראתי לבראנץ׳ דוקס ופשוט פתחתי בקשה למזג למאסטר של אורי... אבל איכשהו במקום, הבקשה מתווספת לפה......

2021-02-11 07:19 UTC, lesagi commented on people/lesagi.json
> +  "description": "מפתח פולסטאק, אוהב שפות, אוהב אלגוריתמים ועושה צעדים ראשונים בתרומה לקוד פתוח"
אולי אני צריך להגיד את זה אחרת... ה-פי.אר מופיע כחדש, אבל כולל את כל הקומיטים שבוצעו על-ידי, גם אלו שכבר אושרו

2021-02-13 18:45 UTC, MichalPorag approved these changes

2021-02-20 13:43 UTC, closed without merging