Add Tomer Brisker
urish/pull-request-community pull request #77
Opened 2021-03-06 18:58 UTC by tbrisker

2021-03-06 19:02 UTC, MichalPorag requested changes

2021-03-06 19:02 UTC, MichalPorag commented on people/tbrisker.json
> +    "description": "כותב קוד פתוח מאז 1999, לפעמים גם מקבל על זה כסף."
היי, תודה על השיתוף :) 
אשמח אם תוכל לספר על עצמך קצת מעבר כדי שנוכל להכיר אותך טוב יותר, מה מעניין אותך מה מלהיב אותך בקוד ומחוץ לקוד :) 
אם אתה לא רוצה תעדכן ואאשר ככה אבל אני מאוד אשמח אם תוסיף

2021-03-06 20:25 UTC, tbrisker commented on people/tbrisker.json
> +    "description": "כותב קוד פתוח מאז 1999, לפעמים גם מקבל על זה כסף."
עדכנתי :)

2021-03-07 04:40 UTC, MichalPorag approved these changes

2021-03-07 04:40 UTC, merged